// ==========================================
// Z-Anonyme — French UI Strings
// ==========================================

export const strings = {
    // App
    appName: "Z-Anonyme",
    appDescription: "Recevez des messages anonymes de vos amis et collègues.",
    appTagline: "Dites-le anonymement.",

    // Navigation
    nav: {
        home: "Accueil",
        inbox: "Boîte de réception",
        links: "Mes liens",
        settings: "Paramètres",
        admin: "Administration",
        login: "Connexion",
        logout: "Déconnexion",
        users: "Utilisateurs",
        reports: "Signalements",
        stats: "Statistiques",
    },

    // Auth
    auth: {
        loginTitle: "Connexion",
        loginSubtitle: "Connectez-vous pour recevoir des messages anonymes.",
        loginWithGoogle: "Continuer avec Google",
        loggingIn: "Connexion en cours...",
        logoutConfirm: "Êtes-vous sûr de vouloir vous déconnecter ?",
    },

    // Messages
    messages: {
        title: "Boîte de réception",
        empty: "Aucun message pour le moment.",
        emptySubtitle: "Partagez votre lien pour recevoir des messages anonymes.",
        new: "Nouveaux",
        read: "Lus",
        archived: "Archivés",
        all: "Tous",
        search: "Rechercher un message...",
        markRead: "Marquer comme lu",
        markUnread: "Marquer comme non lu",
        archive: "Archiver",
        unarchive: "Désarchiver",
        delete: "Supprimer",
        deleteConfirm: "Êtes-vous sûr de vouloir supprimer ce message ?",
        report: "Signaler",
        selected: "sélectionné(s)",
        loadMore: "Charger plus",
        detail: "Détail du message",
        receivedAt: "Reçu le",
        via: "via",
        actions: "Actions",
        bulkActions: "Actions groupées",
        selectAll: "Tout sélectionner",
        deselectAll: "Tout désélectionner",
        characters: "caractères",
    },

    // Public message form
    publicForm: {
        title: "Envoyer un message anonyme",
        subtitle: "Votre identité restera complètement anonyme.",
        placeholder: "Écrivez votre message ici...",
        send: "Envoyer le message",
        sending: "Envoi en cours...",
        charCount: "caractères",
        maxChars: "Maximum 500 caractères",
        minChars: "Minimum 1 caractère",
        success: "Message envoyé !",
        error: "Erreur lors de l'envoi du message.",
        linkExpired: "Ce lien a expiré.",
        linkInactive: "Ce lien n'est plus actif.",
        linkMaxReached: "Le nombre maximum de messages a été atteint.",
        userNotFound: "Utilisateur introuvable.",
        rateLimited: "Trop de messages envoyés. Réessayez plus tard.",
    },

    // Sent / Thank you
    sent: {
        title: "Message envoyé !",
        subtitle: "Votre message a été transmis anonymement.",
        description: "Le destinataire ne pourra pas connaître votre identité.",
        sendAnother: "Envoyer un autre message",
        backHome: "Retour à l'accueil",
    },

    // Links
    links: {
        title: "Mes liens",
        empty: "Aucun lien créé.",
        emptySubtitle: "Créez un lien pour commencer à recevoir des messages.",
        create: "Créer un lien",
        edit: "Modifier",
        delete: "Supprimer",
        copyLink: "Copier le lien",
        copied: "Lien copié !",
        publicLink: "Lien public",
        shareLink: "Lien de partage",
        name: "Nom du lien",
        namePlaceholder: "Ex: Mon lien Instagram",
        active: "Actif",
        inactive: "Inactif",
        expiresAt: "Expire le",
        noExpiry: "Pas d'expiration",
        maxMessages: "Messages maximum",
        noLimit: "Illimité",
        messageCount: "Messages reçus",
        rotateToken: "Renouveler le token",
        rotateConfirm: "L'ancien lien sera désactivé. Continuer ?",
        status: "Statut",
        created: "Créé le",
    },

    // Settings
    settings: {
        title: "Paramètres",
        profile: "Profil",
        username: "Nom d'utilisateur",
        usernamePlaceholder: "votre-pseudo",
        usernameHint: "Lettres, chiffres et tirets. 3-30 caractères.",
        usernameTaken: "Ce nom d'utilisateur est déjà pris.",
        displayName: "Nom affiché",
        displayNamePlaceholder: "Votre nom",
        email: "E-mail",
        notifications: "Notifications",
        emailNotifications: "Notifications par e-mail",
        emailNotificationsDesc: "Recevoir un e-mail pour chaque nouveau message.",
        privacy: "Confidentialité",
        showOnlineStatus: "Afficher le statut en ligne",
        allowPublicProfile: "Profil public visible",
        save: "Enregistrer",
        saving: "Enregistrement...",
        saved: "Paramètres enregistrés !",
        dangerZone: "Zone dangereuse",
        deleteAccount: "Supprimer le compte",
        deleteAccountConfirm: "Cette action est irréversible. Tous vos messages et liens seront supprimés.",
    },

    // Admin
    admin: {
        title: "Administration",
        overview: "Vue d'ensemble",
        totalUsers: "Utilisateurs",
        totalMessages: "Messages",
        totalReports: "Signalements",
        activeLinks: "Liens actifs",
        users: {
            title: "Utilisateurs",
            search: "Rechercher un utilisateur...",
            role: "Rôle",
            status: "Statut",
            actions: "Actions",
            suspend: "Suspendre",
            activate: "Activer",
            makeAdmin: "Nommer admin",
            removeAdmin: "Retirer admin",
            joinedAt: "Inscrit le",
        },
        reports: {
            title: "Signalements",
            open: "Ouverts",
            resolved: "Résolus",
            resolve: "Résoudre",
            deleteMessage: "Supprimer le message",
            suspendUser: "Suspendre l'utilisateur",
            reason: "Raison",
            note: "Note",
            reporter: "Signalé par",
            reportedAt: "Signalé le",
        },
    },

    // Report dialog
    reportDialog: {
        title: "Signaler ce message",
        reason: "Raison du signalement",
        reasonPlaceholder: "Sélectionner une raison",
        reasons: {
            spam: "Spam",
            harassment: "Harcèlement",
            inappropriate: "Contenu inapproprié",
            threat: "Menaces",
            other: "Autre",
        },
        note: "Note additionnelle (optionnel)",
        notePlaceholder: "Décrivez pourquoi ce message est problématique...",
        submit: "Envoyer le signalement",
        submitting: "Envoi...",
        success: "Signalement envoyé.",
    },

    // Common
    common: {
        loading: "Chargement...",
        error: "Une erreur est survenue.",
        retry: "Réessayer",
        cancel: "Annuler",
        confirm: "Confirmer",
        save: "Enregistrer",
        close: "Fermer",
        back: "Retour",
        next: "Suivant",
        yes: "Oui",
        no: "Non",
        or: "ou",
        and: "et",
        darkMode: "Mode sombre",
        lightMode: "Mode clair",
    },
} as const;
